using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.IO;
using System.Text;
using System.Windows.Forms;

namespace FellowshipFinderUser
{
    public partial class Form8 : Form
    {
        SqlConnection con = new SqlConnection(@"Data Source=DESKTOP-HCIEA1E\SQLEXPRESS;Initial Catalog=fellowshipUsers;Integrated Security=True");
        string gender;

        public Form8()
        {
            InitializeComponent();
        }

        private void textBox6_TextChanged(object sender, EventArgs e)
        {

        }
 
        private void button1_Click(object sender, EventArgs e)
        {

        }

        private void button2_Click(object sender, EventArgs e)
        {

        }

        private string openFileExplorer(PictureBox pictureBox, string imageLocation)
        {
            OpenFileDialog file = new OpenFileDialog();
            file.Filter = "png files (*.png)|*.png|jpg files (*.jpg)|*.jpg";

            if (file.ShowDialog() == DialogResult.OK)
            {
                imageLocation = file.FileName.ToString();
                pictureBox.ImageLocation = imageLocation;

            }
            return imageLocation;
        }


        private void button3_Click(object sender, EventArgs e)
        {
            saveToDatabase();
            this.Hide();

        }

        private string getGender()
        {

            if (radioButton1.Checked)
            {
                gender = radioButton1.Text;
            }
            else if (radioButton2.Checked)
            {
                gender = radioButton2.Text;

            }
            else if (radioButton3.Checked)
            {
                gender = radioButton3.Text;

            }
            else if (radioButton4.Checked)
            {
                gender = radioButton4.Text;

            }
            else
            {
                gender = "Rather not say";
            }

            return gender;
        }


     



        private void saveToDatabase()
        {

            string genderChoosen = getGender();
            string autoGeneratedAbout = "Hi, I am " + textBox3.Text;


            if (isValid())
            {
                string query0 = "Select * from fellowshipUsersList where userName='" + textBox3.Text + "'";
                SqlDataAdapter sda = new SqlDataAdapter(query0, con);

                DataTable dtbl = new DataTable();
                sda.Fill(dtbl);

                if (dtbl.Rows.Count == 1)
                {
                    MessageBox.Show("UserName already taken");

                }
                else
                {
                    try
                    {

                        con.Open();

                        string query = "INSERT INTO fellowshipUsersList(userName,Fullname,password,email,dateOfBirth,gender,about) values(@userName,@FullName,@password,@email,@dob,@gender,@about)";
                        string query1 = "INSERT INTO fellows(userName) values(@userName)";
                        string query2 = "INSERT INTO Posts(userName) values(@userName)";
                        string query3 = "INSERT INTO groups(userName) values(@userName)";
                        string query4 = "INSERT INTO groupInvitations(userName) values(@userName)";
                        string query5 = "INSERT INTO fellowRequestsSent(userName) values(@userName)";
                        string query6 = "INSERT INTO fellowRequestsRecieved(userName) values(@userName)";
                        string query7 = "INSERT INTO groupYouManage(userName) values(@userName)";


                        SqlCommand cmd1 = new SqlCommand(query1, con);
                        cmd1.Parameters.AddWithValue("@userName", textBox3.Text);
                        cmd1.ExecuteNonQuery();

                        SqlCommand cmd2 = new SqlCommand(query2, con);
                        cmd2.Parameters.AddWithValue("@userName", textBox3.Text);
                        cmd2.ExecuteNonQuery();

                        SqlCommand cmd3 = new SqlCommand(query3, con);
                        cmd3.Parameters.AddWithValue("@userName", textBox3.Text);
                        cmd3.ExecuteNonQuery();

                        SqlCommand cmd4 = new SqlCommand(query4, con);
                        cmd4.Parameters.AddWithValue("@userName", textBox3.Text);
                        cmd4.ExecuteNonQuery();

                        SqlCommand cmd5 = new SqlCommand(query5, con);
                        cmd5.Parameters.AddWithValue("@userName", textBox3.Text);
                        cmd5.ExecuteNonQuery();

                        SqlCommand cmd6 = new SqlCommand(query6, con);
                        cmd6.Parameters.AddWithValue("@userName", textBox3.Text);
                        cmd6.ExecuteNonQuery();

                        SqlCommand cmd7 = new SqlCommand(query7, con);
                        cmd7.Parameters.AddWithValue("@userName", textBox3.Text);
                        cmd7.ExecuteNonQuery();

                        SqlCommand cmd = new SqlCommand(query, con);
                        cmd.Parameters.AddWithValue("@userName", textBox3.Text);
                        cmd.Parameters.AddWithValue("@Fullname", textBox1.Text);
                        cmd.Parameters.AddWithValue("@password", textBox2.Text);
                        cmd.Parameters.AddWithValue("@email", textBox4.Text);
                        cmd.Parameters.AddWithValue("@dob", dateTimePicker1.Value.Date.ToString("M/d/yyyy"));
                        cmd.Parameters.AddWithValue("@gender", genderChoosen);
                        cmd.Parameters.AddWithValue("@about", autoGeneratedAbout);


                        int N = cmd.ExecuteNonQuery();
                        con.Close();

                        MessageBox.Show("Account Created Successfully", "", MessageBoxButtons.OK, MessageBoxIcon.Information);

                    }
                    catch (Exception ex)
                    {
                        MessageBox.Show(ex.Message, "", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                    finally
                    {
                        con.Close();
                    }
                }

            }
            else
            {
                MessageBox.Show("Please fill the data", "", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }



        }







        private void button4_Click(object sender, EventArgs e)
        {
            con.Open();

            SqlCommand cmd = new SqlCommand("select ProfilePic from fellowshipAdminDetails where AdminId=111", con);

            SqlDataAdapter da = new SqlDataAdapter(cmd);

            DataSet ds = new DataSet();

            da.Fill(ds);

            if (ds.Tables[0].Rows.Count > 0)

            {

                MemoryStream ms = new MemoryStream((byte[])ds.Tables[0].Rows[0]["ProfilePic"]);

                pictureBox1.Image = new Bitmap(ms);

            }
        }

        private void radioButton1_CheckedChanged(object sender, EventArgs e)
        {

        }

        private void Form8_Load(object sender, EventArgs e)
        {

        }

        bool isValid()
        {

            if (string.IsNullOrEmpty(textBox1.Text))
            {
                return false;
            }
            else if (string.IsNullOrEmpty(textBox2.Text))
            {

                return false;
            }
            else if (string.IsNullOrEmpty(textBox3.Text))
            {
                return false;

            }
            else if (string.IsNullOrEmpty(textBox4.Text))
            {

                return false;

            }
            else if (string.IsNullOrEmpty(textBox5.Text))
            {

                return false;
            }
            else
            {
                return true;
            }

        }


        private void textBox3_TextChanged(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(textBox3.Text))
            {
                errorProvider1.Clear();
                errorProvider2.Clear();
            }
            else
            {
                string query0 = "Select * from fellowshipUsersList where userName='" + textBox3.Text + "'";
                SqlDataAdapter sda = new SqlDataAdapter(query0, con);

                DataTable dtbl = new DataTable();
                sda.Fill(dtbl);

                if (dtbl.Rows.Count == 1)
                {
                    errorProvider2.Clear();
                    errorProvider1.SetError(textBox3, "Username Taken");

                }
                else
                {
                    errorProvider1.Clear();
                    errorProvider2.SetError(textBox3, "Correct");
                }
            }
        }

        private void textBox5_TextChanged(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(textBox2.Text) && string.IsNullOrEmpty(textBox5.Text))
            {

                errorProvider1.Clear();
                errorProvider3.Clear();

            }
            else
            {

                if (!(textBox5.Text.Equals(textBox2.Text)))
                {
                    errorProvider3.Clear();
                    errorProvider1.SetError(textBox5, "Password doesn't match");
                }
                else
                {
                    errorProvider1.Clear();
                    errorProvider3.SetError(textBox5, "Correct");
                }
            }
        }

        private void textBox2_TextChanged(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(textBox2.Text))
            {

                errorProvider1.Clear();
                errorProvider4.Clear();

            }
            else
            {
                if (textBox2.Text.Length < 8)
                {
                    errorProvider4.Clear();
                    errorProvider1.SetError(textBox2, "Minimum password length is 8");
                }
                else
                {
                    errorProvider1.Clear();
                    errorProvider4.SetError(textBox2, "Correct");
                }
            }
        }

        private void pictureBox2_Click(object sender, EventArgs e)
        {
            textBox2.UseSystemPasswordChar = true;
            pictureBox3.Visible = true;
        }

        private void pictureBox4_Click(object sender, EventArgs e)
        {
            textBox5.UseSystemPasswordChar = false;
            pictureBox4.Visible = false;
        }

        private void pictureBox3_Click(object sender, EventArgs e)
        {
            textBox2.UseSystemPasswordChar = false;
            pictureBox3.Visible = false;
        }

        private void pictureBox5_Click(object sender, EventArgs e)
        {  
            textBox5.UseSystemPasswordChar = true;
            pictureBox4.Visible = true;

        }

        private void textBox1_TextChanged(object sender, EventArgs e)
        {

        }

        private void textBox1_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                e.Handled = true;
                e.SuppressKeyPress = true;
                this.SelectNextControl(textBox3, true, true, true, true);
                textBox3.Focus();

            }
        }

        private void textBox3_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                e.Handled = true;
                e.SuppressKeyPress = true;
                this.SelectNextControl(textBox2, true, true, true, true);
                textBox2.Focus();

            }
        }

        private void textBox2_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                e.Handled = true;
                e.SuppressKeyPress = true;
                this.SelectNextControl(textBox5, true, true, true, true);
                textBox5.Focus();

            }
        }

        private void textBox5_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                e.Handled = true;
                e.SuppressKeyPress = true;
                this.SelectNextControl(textBox4, true, true, true, true);
                textBox4.Focus();

            }
        }

        private void textBox4_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                e.Handled = true;
                e.SuppressKeyPress = true;
                this.SelectNextControl(dateTimePicker1, true, true, true, true);

            }
        }

        private void dateTimePicker1_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                e.Handled = true;
                e.SuppressKeyPress = true;
                this.SelectNextControl(radioButton1, true, true, true, true);

            }
        }

        private void radioButton1_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                e.Handled = true;
                e.SuppressKeyPress = true;
                this.SelectNextControl(radioButton2, true, true, true, true);


            }
        }

        private void radioButton3_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                e.Handled = true;
                e.SuppressKeyPress = true;
                this.SelectNextControl(radioButton4, true, true, true, true);


            }
        }

        private void radioButton2_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                e.Handled = true;
                e.SuppressKeyPress = true;
                this.SelectNextControl(radioButton3, true, true, true, true);

            }
        }

        private void radioButton4_CheckedChanged(object sender, EventArgs e)
        {

        }

        private void radioButton4_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                button3.PerformClick();

            }
        }
    }
}
